### ISSUE TITLE
Streamlit UI - Weights and Biases login

### ISSUE THREAD

**Issue by andreim14** [lucmos/nn-template#7]
The template is really awesome. 

I had a small issue. When I run the Streamlit UI without being logged in in Weights and Biases. The UI just hanged with the loading status without giving me any feedback about what was happening, so that I have to log in first in wandb. 
I had to login manually from the console. Is there any way to solve this issue? For example to have feedback from the UI if I'm not logged in.

Thanks!

**Comment by Flegyas** [comment]
Thanks for the issue! I've fixed it in https://github.com/lucmos/nn-template/commit/83d764bb6bac0b58e31bfd5f7b35cd1847b32bf0 .
